# Generated by Django 4.1.7 on 2023-03-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'All Post'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'All Post'},
        ),
    ]
