# Generated by Django 4.1.7 on 2023-03-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_delete_featuredimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
